### ISSUE TITLE
What issues need to be resolved before we can consider releasing o-ft-forms 1.0.0?

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-ft-forms#33]
It would be good to get o-ft-forms to a 1.0.0 for the release on the sign up app. It's might not be possible to resolve all outstanding issues prior to the MVP launch but my thoughts are the following are essential:

Use o-ft-icons for icons #14
Prefixes and suffixes are broken #21
Down arrow icon on the right on dropdowns - incorrect #24
Clarify browser support #30

Any thoughts are welcome.

**Comment by kaelig** [comment]
See the remaining issues for the [v1 milestone](https://github.com/Financial-Times/o-ft-forms/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0).
