### ISSUE TITLE
Duplication of native and custom drop down icons in select boxes 

### ISSUE THREAD

**Issue by mod-jeremyredding** [Financial-Times/o-ft-forms#56]
![capture](https://cloud.githubusercontent.com/assets/8138004/3974396/eb80bd98-27f3-11e4-95d2-36f8f5c5dcc3.JPG)

In Firefox ( at least version 31.0), both the native browser drop down icon and the custom icon is visible.

**Comment by kaelig** [comment]
I can't reproduce this bug in Yosemite…

**Comment by kaelig** [comment]
Closing, since it's been fixed in:
- Yosemite (all versions of Firefox)
- Firefox 35 (all platforms)
