### ISSUE TITLE
Form element height

### ISSUE THREAD

**Issue by danskinner** [Financial-Times/o-ft-forms#57]
We currently have buttons in two sizes, 24px (14px text) and 36px (16px text). The form elements are only in the larger size.

- [ ] Firstly, the height of the form elements varies from 36px. Input fields are 35 and selects are 33px. These both need to be fixed with their respective padding to get them to 36px.
- [ ] Secondly, we need to have a matching smaller size of 24px. Reducing the text to 14px and amending the padding is all that's needed. We originally agreed that forms, being forms, needed to be large and clear at all times, but the author alerts overlay has shown the need for a smaller size to match the smaller buttons.

@pauloneillft @SarahHornsey @silkesd, anyone not agree?

**Comment by kaelig** [comment]
- Select and input sizes seem to have been fixed for a while now
- Checkbox and radio buttons sizes are been fixed in v1 beta
