### ISSUE TITLE
Add a 'read only' field in forms

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/o-ft-forms#82]
Hi there,

Please can we add a 'read only' field in the forms module. This is a field element that is none editable. I've attached a mock-up and some production notes here... http://stackoverflow.com/questions/7730695/whats-the-difference-between-disabled-disabled-and-readonly-readonly-for-ht#answer-7730719 @jamesnicholls 

![me002-signup-directdebit-address](https://cloud.githubusercontent.com/assets/8235225/5778776/a64d9df0-9d95-11e4-8c1f-60950382a110.png)

Thanks, Sarah

**Comment by kaelig** [comment]
Not sure what the benefit of this is, considering that visual pattern could be achieved using simple text.

**Comment by SarahHornsey** [comment]
But a third party, etc who is looking for 'read only' field will need to know that this is the preferred style of the FT. For example, they won't make up there own style which could be slightly different. If we don't document it or include it as a component then other developers and designers are free to do their own thing.

**Comment by kaelig** [comment]
Just to take a step back: originally readonly and disabled fields look the same, either in the browser or in a UI library like bootstrap.

Now back to this discussion: I understand what the screenshot is suggesting but isn't that a UX pattern (achievable by other means / here with simple text)? Is it something the presentational layer should do by default? I'm all for "sensible defaults" but I'm not entirely sure this principle applies here.

**Comment by SarahHornsey** [comment]
Hi Kaelig, Sorry! I am so confused by your response. Can you elaborate a bit? Happy to meet up chat / discuss if this is easier. If this is something we really shouldn't do then I'm happy to take your steer on this but I'm just not sure I understand. Thanks, Sarah

**Comment by kaelig** [comment]
Sarah, sorry this is confusing, let's discuss face to face when I'm at the office tomorrow.

**Comment by SarahHornsey** [comment]
Great. Sounds good to me.

**Comment by kaelig** [comment]
As discussed with @SarahHornsey, @jamesnicholls and @Thurst-ft: we're going to build a new class that "unskins" fields: #83
